[package]
name = "chipioindustries/replication-middleware"
description = "Middleware for replicating Rodux actions to clients."
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]

[dev-dependencies]
TestEZ = "roblox/testez@0.4.1"